name: type_gen

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  source_gen: ^0.9.10+1
  build_runner: ^1.10.9
  analyzer: ^0.41.1
  polkadot_dart:
    path: '..'
